name: secrete
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0'

dependencies:
  csv: ^5.0.1
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.3.6
  flutter_secure_storage: ^8.0.0
  flutter_slidable: ^3.0.0
  fluttertoast: ^8.2.2
  hexcolor: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  hooks_riverpod: ^2.3.6
  intl: ^0.18.1
  local_auth: ^2.1.6
  path_provider: ^2.0.15
  url_launcher: ^6.1.11
  uuid: ^3.0.7

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_launcher_icons:
  android: "assets/logo/logo.png"
  ios: false
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  image: "assets/logo/logo.png"
  color: "#ffffff"
  color_dark: "#262424"
  ios: false
  web: false

flutter:
  uses-material-design: true

  assets:
    - ".env"
    - "assets/logo/"
    - "assets/images/"
    - "assets/files/"
